report_title: "Blueberry Genotyping Report"
report_comment: "Main quality statistics"

# 1. Força o Trimmomatic a usar o nome do arquivo de log (seu $sample)
trimmomatic_config:
    s_name_filenames: true

# 2. Organiza a ordem das seções
report_section_order:
    trimmomatic: 10
    samtools: 20
    picard: 30
    mosdepth: 40
    bcftools: 50

# 3. Configura a Tabela de Estatísticas Gerais
table_columns_visible:
    Trimmomatic: True
    Samtools: True
    Mosdepth: True
    BCFTools: False

# 4. Limpeza agressiva de nomes (essencial para agrupar as linhas)
extra_fn_clean_exts:
    - ".trim.log"
    - ".stats.txt"
    - ".raw.sort.norm.vcf.gz"
    - ".sorted.bam"

# 5. Backup de limpeza de sufixos
sample_names_replace_suffixes:
    - ".sorted.group.rmdup"
    - ".sorted.group"
    - ".sorted"
    - ".trim"
    - "_paired"

# 6. Tabela separada para Variantes (BCFTools)
custom_data:
    bcftools_stats:
        parent_id: bcftools
        parent_name: "Variant Calling Stats"
        section_name: "Variant per Chromossomo"
        description: "Scaffold statistics."
